
name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

   

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "polar-harbor-58989" #Must be unique in Heroku
          heroku_email: "jomilojuajibola@gmail.com"
          healthcheck: " https://polar-harbor-58989.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true